version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: make
          command: |
            make
      - store_test_results:
          path: test-reports-circle
      - store_artifacts:
          path: test-reports
workflows:
  build_test:
    jobs:
      - run_tests
      
